### ISSUE TITLE
Consider revising correlation to a single object

### ISSUE THREAD

**Issue by OR13** [transmute-industries/universal-wallet#7]
This would let us remove a field from each object, and centralize the privacy information issues to single object.

For example, when transferring currency to a new account, we would update a single correlation object to reflect the new disclosure, not the currency and key objects.

**Comment by OR13** [comment]
@gjgd I would love to hear your thoughts on this. How best to express the privacy related concepts in the data model?

**Comment by gjgd** [comment]
I agree, I think it makes sense to have one correlation object that is updated with the following info:
- The subject key
- A list of where the key is used  (eg: used for Bitcoin address and assertion method in did:example:123) 
- A list of when the key was used (eg: 2 cryptocurrency transfer and one digital signature)

The more either list grows, the more correlation there is and the more info can be learnt about the holder of the subject key

**Comment by OR13** [comment]
related... https://github.com/transmute-industries/universal-wallet/issues/11

In the code this ^ issue references, we end up building a single id based index... so it seems that this structure is at the very least, already implied.
