### ISSUE TITLE
Describe Interfaces / Relationship to Agents

### ISSUE THREAD

**Issue by OR13** [transmute-industries/universal-wallet#8]
The purpose of the interfaces section is to provide a set of functions that take wallet contents as input and produce wallet contents as output, such that an agent / wallet app that follows the spec and has been used some amount can be exported and imported into a new app, and the history of activity will be preserved, if the first wallet chose to implement the interfaces concretely.

In other words, the interfaces as they appear in the spec are just suggestions, and they are expected to be made concrete and supported to varying degrees by implementations.

One fear is that without describing them, wallets might just focus on just currency or just credentials... and then portability would be harmed, because you would need to pick a new wallet that supported the same interfaces as your old one... and no obvious way to tell which interfaces were supported, because they are not defined anywhere....

Its not the end of the world, if you can't transfer your ETH, but you can still present credentials when switching wallets.... but ideally choosing products that are conforming to this specification would give you support for both the data and popular features built on it, regardless of which wallet vendor you chose.

The spec needs informative text to make this clearer.

**Comment by TelegramSam** [comment]
I think including the interfaces in the spec is likely to slow its progress and adoption. 

I think the interface work is valuable, but may be more applicable in another spec/document. Part of the disconnect here is the different ideas around what a wallet is, and how you interface with one. (Examples: Wallet is a separate piece of code, vs wallet fully contained within an agent.)

**Comment by OR13** [comment]
thanks for raising this, I'm trying to work through this issue on the CCG mailing list as well.

As i noted there, we want some way to know if a wallet support "transfer currency" or "prove indy credential", we didn't feel like just defining what an "indy connection", "indy schema" or "ethereum address" was sufficient for wallet vendors to support that.

In other words... how do we know what features a wallet supports?

**Comment by TelegramSam** [comment]
one basic way would be to indicate which data objects it will understand during import/export. That assumes that if I import a ethereum address I support _all_ of the 'ethereum actions', but it is a start.
