### ISSUE TITLE
Align With Hyperledger Wallets

### ISSUE THREAD

**Issue by OR13** [transmute-industries/universal-wallet#9]
https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0050-wallets
https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0051-dkms

**Comment by OR13** [comment]
Seems our of scope for this spec... but https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/design/011-wallet-query-language/README.html

defines a wallet query language... that operates on encrypted tags... similar to the concept of encrypted indexes in EDVs.

**Comment by andrewwhitehead** [comment]
Yes, I've got an implementation of WQL in there. I'm not quite sure how to reconcile the simple named tags with tag-value pairs yet.

I agree there's some crossover with secure data vaults but I'm leaving that for later if there's some compatibility gains to be made.

Regarding the layering, this library would need direct access to the KMS, assuming it performs the encryption and decryption operations. So I'm assuming D and E are inverted at the moment, or at least side-by-side, and the concrete wallet implementation would consist of one or more data vaults instantiated with KMS references.

**Comment by OR13** [comment]
@andrewwhitehead yes, D + E could be siblings... one might ask a KMS to help you decrypt encrypted chunks, or authenticate to the encrypted chunk provider, but in both cases the "wallet software / agent software" is doing that work.... I layered them like that because I assumed the strongest case where the KMS is required to help authenticate the wallet to the storage provider, and to decrypt its contents.
